{% set name = "psy-maps" %}
{% set version = "1.3.0" %}
{% set sha256 = "3d3314c8bec58fb0956712b9524388edf010375142af89a94342369485ac5a88" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - psyplot
    - psy-simple
    - cartopy

test:
  imports:
    - psy_maps

about:
  home: https://github.com/Chilipp/psy-maps
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: Psyplot plugin for visualization on a map

  description: |
    This psyplot plugin uses the cartopy package to visualize geo-referenced
    data on a map
  doc_url: http://psyplot.readthedocs.io/projects/psy-maps
  dev_url: https://github.com/Chilipp/psy-maps

extra:
  recipe-maintainers:
    - Chilipp
