{% set name = "psy-maps" %}
{% set version = "1.5.0" %}
{% set sha256 = "863973cf2614ab1254ff9a27a1a7afbe06b5acafe3aff16fdbbe1bcb7538f3e3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install . --no-deps --ignore-installed -vvv
  skip: true  # [py == 36]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - {{ pin_compatible('psy-simple', max_pin='x.x') }}
    - cartopy
    - scipy

test:
  imports:
    - psy_maps

about:
  home: https://github.com/psyplot/psy-maps
  license: LGPL-3.0-only
  license_family: GPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: Psyplot plugin for visualization on a map

  description: |
    This psyplot plugin uses the cartopy package to visualize geo-referenced
    data on a map
  doc_url: https://psyplot.github.io/psy-maps
  dev_url: https://github.com/psyplot/psy-maps

extra:
  recipe-maintainers:
    - Chilipp
