{% set name = "psy-maps" %}
{% set version = "1.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/psy-maps-{{ version }}.tar.gz
  sha256: 86bf703469fe1282e9cc142d15158df7ac01a6115eb31ae764452bf5f11c4e4e

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - {{ pin_compatible('psyplot', max_pin='x.x') }}
    - {{ pin_compatible('psy-simple', max_pin='x.x') }}
    - cartopy
    - scipy

test:
  imports:
    - psy_maps

about:
  home: https://github.com/psyplot/psy-maps
  license: LGPL-3.0-only
  license_family: GPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: Psyplot plugin for visualization on a map

  description: |
    This psyplot plugin uses the cartopy package to visualize geo-referenced
    data on a map
  doc_url: https://psyplot.github.io/psy-maps
  dev_url: https://github.com/psyplot/psy-maps

extra:
  recipe-maintainers:
    - Chilipp
