travis:
  secure:
    BINSTAR_TOKEN: YWD5vXBOciFbK8o/F0gVrN4bQHny96GqwHOagWiBAZ5qTdS7Aq6IF0KPB0Cv9rsCw1QxyXVz2202SGT+jvTiPRhHYtkwHk4bbiVOtGT+Ar7elKmomi9JOmO8ehHTMn8fgGVU8Jg0AGLeBNaiySNlc8wu2w1sZ0KHXOhjSJoQD1qJnIvAwIBoCezb9dl0vwNGe7Lii3/RQ/i+9abs34Tkhakg5rAM2uKcJ1inGlmi54/7OHHX1sJtQ8DNxsy6yj9je+3/RRFWtnokQ9x73np4QNCzCsQ1Kg701JSVwvKKuaIx/VEL+5A0fe+RwY2gHjcb/sMSQbtzEa6tTd4IdtuNzrRrecEhN5QNYtfY4gOWnZQgInuO8dXrCss0yIG8il/CmcgoWUytUt5mvJ+PCg+oIvJaUoOxo7zTde3OWsEKJ7BzLBlYKDYDqTpiUBCoyMo69nqqDrK+4V9PVk5S54p5Fg0W6v+utjwe+268c5IXj6Xopw33R43X1L3Cxi+4DVm1eJsOa8APBeadxKXTzfbgAlv2RbcR+2mxcbWLRjnBanKXGPsZWGj0G3ZMHUZa5BpIF9NS0cj1hecTWP97oWKzvSCvKXvSyQuurgQDOVtxm9PqBrf+HMiJgV35/MIUPHl8oVwd+kS2Jg6u3+apAM/64ggPgLYhMvje+O89BRaInQg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
