travis:
  secure:
    BINSTAR_TOKEN: IayRAt7o6pGqurt42bhflNXbY4gyunK+4DaZjXP60xEDsDmlmoLGh/vL93mTmtVTqVJjkw23hjyufs58qoWDkWALCCs8VcWfkDLWTaO2tye6uBzpDHbg2Hv9ezGV6yoaf/j99vDV2wYjv2DiavxKXKmeX90cDTP2oRqFK1O1OqoUbIZ+txLczT+u52An8wE7FzogEkzhQM4IFvzRmYsWEUFRWLUQmnbnbZuZZBNqIm3s2I12lO0VREm5U79kMsekALuamFpfjqlYFb8OAWVLhOMFwmxS6Y3a+E7sG+J9v/PYNEd/bKqs1dADOMHa1rIECDv9hVKSa1HCuf1LmLuLeweea7gM6cxUXyQsc/wrT7tcOM0F+7xk6kMZQOLr5Mk1BbUkMBKQI6ZRAVWFTkidIEgxHDpg7IGXj8NiwcRo1u+rI24VFK0Vfg67CPUSKrq8tfBYiv+HyEICmdZqa4vH5eXYMmN6UPuRSuOng0ECqKgOXu5BaVlz6vC+D8qe2QFR9Xhz+wZvIFLxkhhUj8+1ffH7t17b5IqO76U2tefzobWpptBYpATBT6wO2rPWEbE1MY7XYSSOUK9JNxUqY//tl01BxwJRQ4m6XNJw2NM5jNmMo2WZQ34mzKxMcWO/x1AEQezvMMS3WwUwEmG+/Ko+wXg5N4vI43+cHG/j0SvPAVw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
