appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: 7IUWF3syrEGanSkhu3LA0duRjKKElY0xNSbCO7QiCyMlpz4CEno4KrO2/tpFW8Znr7HLsi4uhVkspq+V7BhnYj9EwsQWdkfrv1VPOL33oXzx0cfhZMqMdbYB5xpaD0NdkMEnBuqFDe2I+cKM47ULiJDb0Ngl6rQVNHtU2s9FsKm5EiL+Vlcr0q9e7I2R80wQRNkj/7TdbXXFJMoqaJrA6rbjYcUXrKeRKsDeEtLCWCG5qDMOasrZnaxH0K9W4XORCuDEBB65OhM91Fp+pMFNx/BbGRBqH0NlNgTzYdJnli00t162QkYnqZstBo/9TF0lH51hi1m69R4aK7NK7P70yfUYPdKqO8FS0rRL4GGxMh5kDJaAhPnxMQ8d5teGsu+4eLhZG31vsHOfokWHnC2xOfW0D2Yp4vze1Jl0xSnEEbI7gwQeZK2HbMhJh7ydR0QbivkYh/fRMRx7UVpFc2LA2EoQqlz/ZfXEFXxH2eV4vbzbam4P/rux9vAJ16zyaG0cXsvTWSXCw9abobbkxmK1IBWcCBNqm4rwBViW6O28tMypVPu8Irr/3LhOnlomEya4x34ITYLApU+qtzeju7lr2X1j+m55T6fo0NbV/ElwJoJLFxyg1hR14AenTAGEfVMRl5l1w/jJPFWJEIYb5rEew4yVXSvMPlbZR89z22o2CRg=}
